using Avalonia.Controls;
using Crustcut.Presentation;

namespace Crustcut.App;

public partial class MainWindow : Window
{
    public MainWindow() : this(new ShellViewModel()) { }

    public MainWindow(ShellViewModel shell)
    {
        // InitializeComponent is generated by the Avalonia XAML compiler; it also assigns
        // the x:Name fields (PageHost). Declaring it by hand shadows that and leaves the
        // fields null.
        InitializeComponent();
        DataContext = shell;
        PageHost.Content = new Views.OverviewView();
    }
}
