using System.ComponentModel;
using Avalonia.Controls;
using Crustcut.Presentation;

namespace Crustcut.App;

public partial class MainWindow : Window
{
    private readonly ShellViewModel _shell;
    private readonly PageFactory _pages;

    public MainWindow() : this(new ShellViewModel(), null) { }

    public MainWindow(ShellViewModel shell, Composition? app)
    {
        // InitializeComponent is generated by the Avalonia XAML compiler; it also assigns
        // the x:Name fields (PageHost). Declaring it by hand shadows that and leaves the
        // fields null.
        InitializeComponent();

        _shell = shell;
        _pages = new PageFactory(app);
        DataContext = shell;

        _shell.PropertyChanged += OnShellPropertyChanged;
        ShowActivePage();
    }

    private void OnShellPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(ShellViewModel.ActiveTab)) ShowActivePage();
    }

    private void ShowActivePage() => PageHost.Content = _pages.Create(_shell.ActiveTab);

    /// <summary>Switches tab programmatically. Used by the --screenshot debug flag.</summary>
    public void NavigateTo(string tabId) => _shell.NavigateCommand.Execute(tabId);
}
